ENUM <- list(
  divisions = c("Mathematicians and Physicians", "Statesmen and Warriors",
                "Divines and Metaphysicians", "Poets and Artists",
                "Historians, Antiquarians, and Lawyers", "Orators and Critics"),
  occupation = c("Physician",  "Christian Religious Person", "Poet",
                 "Jewish Religious Person",
                 "Historian", "Geographer", "Lawyer", "Philosopher",
                 "Mathematician",
                 "Critic", "Pope", "Christian Father", "Orator", "Architect",
                 "Painter", "Musician", "Muslim Religious Person", "Antiquary",
                 "Metaphysician", "Moralist", "Actor", "Statuary", "Writer",
                 "Printer",
                 "Chemist", "Political Writer", "Chronologer", "Traveller",
                 "Engineer", "Engraver", "Politician/Military Person"),
  occupation_abbr = c("Ph", "D", "P", "J", "H", "Geo", "L", "H P", "M", "Cr",
                      "Po", "F", "Or", "Ar", "Pa", "Mu", "Moh", "Ant", "Met", "Mor",
                      "Act", "St", "Bel", "Pr", "Chy", "Pol", "Ch", "Trav", "Engineer",
                      "Eng"),
  sect_abbr = c("Soc", "Ital", "Ion", "Eleat", "Per", "Cyr", "Ac", "Sto",
                "Cyn", "Meg", "Ep", "Eleack", "Scept"),
  sect = c("Socratic", "Italic", "Ionic", "Eleatic", "Peripatetic",
           "Cyrenaic", "Academic", "Stoic", "Cynic", "Megaric", "Epicurean",
           "Eleack", "Sceptic")
)
