ENUM <- list(
  divisions = c("Mathematicians and Physicians", "Statesmen and Warriors",
                "Divines and Metaphysicians", "Poets and Artists",
                "Historians, Antiquarians, and Lawyers", "Orators and Critics"),
  occupation = c("Actor", "Ancient Greek Philosopher", "Antiquary", "Architect",
                 "Chemist", "Christian Church Father",
                 "Christian Religious Person",
                 "Chronologer", "Critic", "Engineer", "Engraver", "Explorer",
                 "Geographer", "Historian", "Jewish Religious Person", "Lawyer",
                 "Mathematician or Scientist", "Metaphysician", "Musician",
                 "Muslim Religious Person",
                 "Orator", "Painter", "Philosopher", "Physician", "Poet",
                 "Political Writer",
                 "Monarch, Politician, or Military Person", "Pope", "Printer", "Sculptor",
                 "Writer"),
  occupation_abbr = c("Ph", "D", "P", "J", "H", "Geo", "L", "H P", "M", "Cr",
                      "Po", "F", "Or", "Ar", "Pa", "Mu", "Moh", "Ant", "Met", "Mor",
                      "Act", "St", "Bel", "Pr", "Chy", "Pol", "Ch", "Trav", "Engineer",
                      "Eng"),
  sect_abbr = c("Soc", "Ital", "Ion", "Eleat", "Per", "Cyr", "Ac", "Sto",
                "Cyn", "Meg", "Ep", "Eleack", "Scept"),
  sect = c("Socratic", "Italic", "Ionic", "Eleatic", "Peripatetic",
           "Cyrenaic", "Academic", "Stoic", "Cynic", "Megaric", "Epicurean",
           "Eleack", "Sceptic")
)
